num_samples: 5
weights: '0.35, 0.25, 0.2, 0.15, 0.05'
num_out_samples: 5
out_weights: '0.1, 0.2, 0.2, 0.25, 0.25'

linear_vel_max: 2.5
linear_acc_max: 2.0
angular_vel_max: 10.0
angular_acc_max: 10.0
timeout: 0.25